package engine

// The tasks table and check --write (step 5.1.8): built byte-stable from format-0 and format-1 task files; the
// active line as contract section 13's step 2 finds it; a worktree refused; stale a warning only; init writing both
// tables.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/LastStep/Bonsai/internal/format"
	"github.com/LastStep/Bonsai/internal/testpack"
	"github.com/LastStep/Bonsai/internal/workspace"
)

const (
	f0Running = "---\nid: T-0901\ntitle: A format-0 task | with a pipe\nstatus: running\nlane: light\n---\n\n# body\n"
	f0Odd     = "---\nid: T-0010\ntitle: Old\nstatus: In Progress\nstarted: 2026-01-02\n---\n"
	f1Todo    = "---\nformat: bonsai.task/1   # fields: bonsai check --schema bonsai.task\nid: T-0902\ntitle: A task not started\nstatus: todo\n" +
		"lane: light\ndone_when: []\ndepends_on: []\nblocked_by:\ncreated: 2026-10-09\nstarted:\nfinished:\nlabels: {}\n---\n"
	f1Done = "---\nformat: bonsai.task/1\nid: T-100000\ntitle: Done long ago\nstatus: done\nlane:\ndone_when: []\ndepends_on: []\n" +
		"blocked_by:\ncreated: 2026-09-01\nstarted: 2026-09-02\nfinished: 2026-09-03\nlabels: {}\n---\n"
)

const wantTable = "---\nformat: bonsai.tasks/1   # generated by bonsai check --write from the task files; never edit by hand\n---\n" +
	"Active task when none is named: T-0901\n\n" +
	"| Task | Title | Status | Lane | Started | Finished |\n|---|---|---|---|---|---|\n" +
	"| T-100000 | Done long ago | done | | 2026-09-02 | 2026-09-03 |\n" +
	"| T-0902 | A task not started | todo | light | | |\n" +
	"| T-0901 | A format-0 task \\| with a pipe | running | light | | |\n" +
	"| T-0010 | Old | In Progress | | 2026-01-02 | |\n"

// linked is a project linked to the test pack, with its task folder (work/tasks).
func (e *env) linked(t *testing.T, name string) string {
	t.Helper()
	root := testpack.Project(t, e.tmp, name)
	e.link(t, root, e.pack.A)
	return root
}

func TestTasksTableIsByteStable(t *testing.T) {
	e := setup(t)
	root := e.linked(t, "tables")
	dir := "work/tasks"
	if cfg, err := workspace.LoadConfigFull(root); err != nil || cfg.Full.Documents.Task != dir {
		t.Fatalf("the task folder is not %s: %v", dir, err)
	}
	// init wrote the tables: the tasks table with no rows, the sessions table with its frontmatter and no rows.
	if got := read(t, root, workspace.TasksTableFile); !strings.HasSuffix(got, "Active task when none is named: none (no task reads running)\n\n"+
		"| Task | Title | Status | Lane | Started | Finished |\n|---|---|---|---|---|---|\n") {
		t.Errorf("init's tasks table:\n%s", got)
	}
	if got := read(t, root, workspace.SessionsTableFile); !strings.HasPrefix(got, "---\nformat: bonsai.sessions/1   # generated by bonsai check --write from the log; never edit by hand\n---\n") ||
		strings.Count(got, "\n| ") != 2 {
		t.Errorf("init's sessions table:\n%s", got)
	}
	if _, err := format.ReadSessions([]byte(read(t, root, workspace.SessionsTableFile))); err != nil {
		t.Errorf("init's sessions table does not read back: %v", err)
	}
	for name, content := range map[string]string{"T-0901-a.md": f0Running, "T-0010-b.md": f0Odd, "T-0902-c.md": f1Todo, "T-100000-d.md": f1Done,
		"T-0903-broken.md": "---\nid: [unclosed\n---\n"} {
		writeFile(t, root, dir+"/"+name, content)
	}
	// A broken file: no row, and nothing active (contract section 13: it could be the running one).
	b, err := BuildTasksTable(root, dir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "Active task when none is named: none (a task file does not parse (work/tasks/T-0903-broken.md))\n") ||
		strings.Contains(string(b), "| T-0903 |") {
		t.Errorf("with a broken file:\n%s", b)
	}
	if err := os.Remove(filepath.Join(root, dir, "T-0903-broken.md")); err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 2; i++ {
		b, err = BuildTasksTable(root, dir)
		if err != nil || string(b) != wantTable {
			t.Fatalf("run %d: %v\n%s", i, err, b)
		}
	}
	if _, err := format.ReadTasks(b); err != nil {
		t.Errorf("the table does not read back: %v", err)
	}
	// Two running tasks: none, and why.
	writeFile(t, root, dir+"/T-0902-c.md", strings.Replace(f1Todo, "status: todo", "status: running", 1))
	if b, _ = BuildTasksTable(root, dir); !strings.Contains(string(b), "Active task when none is named: none (two or more tasks read running (T-0901, T-0902))\n") {
		t.Errorf("two running:\n%s", b)
	}
	// BONSAI_TASK never changes the table.
	t.Setenv(workspace.TaskEnv, "T-0010")
	if b2, _ := BuildTasksTable(root, dir); string(b2) != string(b) {
		t.Errorf("the environment changed the table:\n%s", b2)
	}
}

func TestWriteTables(t *testing.T) {
	e := setup(t)
	root := testpack.Project(t, e.tmp, "write")
	for name, content := range map[string]string{"T-0901-a.md": f0Running, "T-0010-b.md": f0Odd, "T-0902-c.md": f1Todo, "T-100000-d.md": f1Done} {
		writeFile(t, root, "work/tasks/"+name, content)
	}
	// init builds the tasks table as --write would, from the task files already there.
	e.link(t, root, e.pack.A)
	if got := read(t, root, workspace.TasksTableFile); got != wantTable {
		t.Fatalf("init's table with tasks:\n%s", got)
	}
	if r, err := checkLocal(t, root, e.home); err != nil || len(r.Findings) != 0 || len(r.Warnings) != 0 {
		t.Fatalf("a fresh link: %v %+v %+v", err, r.Findings, r.Warnings)
	}
	// A task moves: the table is stale until written, a warning and never a finding.
	writeFile(t, root, "work/tasks/T-0902-c.md", strings.Replace(f1Todo, "status: todo", "status: plan", 1))
	r, err := checkLocal(t, root, e.home)
	if err != nil || len(r.Findings) != 0 || len(r.Warnings) != 1 || r.Warnings[0].Code != "tables" || r.Warnings[0].File != workspace.TasksTableFile ||
		r.Warnings[0].Next != "run: bonsai check --write" || r.Warnings[0].Who != "agent" {
		t.Fatalf("a stale table: %v %+v %+v", err, r.Findings, r.Warnings)
	}
	wantAfter := strings.Replace(wantTable, "| T-0902 | A task not started | todo |", "| T-0902 | A task not started | plan |", 1)
	res, werr := WriteTables(root)
	if werr != nil || len(res.Written) != 1 || read(t, root, workspace.TasksTableFile) != wantAfter {
		t.Fatalf("write: %v %+v\n%s", werr, res, read(t, root, workspace.TasksTableFile))
	}
	if r, err = checkLocal(t, root, e.home); err != nil || len(r.Warnings) != 0 || len(r.Findings) != 0 {
		t.Errorf("after the write: %v %+v %+v", err, r.Findings, r.Warnings)
	}
	// Twice: the same bytes, and nothing rewritten. A CRLF checkout of the table is the same table.
	before := snapshot(t, root)
	if res, werr = WriteTables(root); werr != nil || len(res.Written) != 0 || len(res.Same) != 1 || snapshot(t, root)[workspace.TasksTableFile] != before[workspace.TasksTableFile] {
		t.Errorf("second write: %v %+v", werr, res)
	}
	writeFile(t, root, workspace.TasksTableFile, strings.ReplaceAll(wantAfter, "\n", "\r\n"))
	if r, _ = checkLocal(t, root, e.home); len(r.Warnings) != 0 {
		t.Errorf("a CRLF table: %+v", r.Warnings)
	}
	// A hand edit that still reads: a warning; one that does not read: the finding document, no warning.
	writeFile(t, root, workspace.TasksTableFile, strings.Replace(wantAfter, "| T-0010 | Old |", "| T-0010 | Older |", 1))
	if r, _ = checkLocal(t, root, e.home); len(r.Findings) != 0 || len(r.Warnings) != 1 || r.Warnings[0].Code != "tables" {
		t.Errorf("an edited table: %+v %+v", r.Findings, r.Warnings)
	}
	writeFile(t, root, workspace.TasksTableFile, "not a table\n")
	if r, _ = checkLocal(t, root, e.home); len(r.Findings) != 1 || r.Findings[0].Code != "document" || len(r.Warnings) != 0 {
		t.Errorf("a broken table: %+v %+v", r.Findings, r.Warnings)
	}
	// --write rebuilds it whole, a broken one too; a missing one is written.
	if res, werr = WriteTables(root); werr != nil || len(res.Written) != 1 || read(t, root, workspace.TasksTableFile) != wantAfter {
		t.Errorf("rebuild of a broken table: %v %+v", werr, res)
	}
	if err := os.Remove(filepath.Join(root, workspace.TasksTableFile)); err != nil {
		t.Fatal(err)
	}
	if r, _ = checkLocal(t, root, e.home); len(r.Warnings) != 1 || r.Warnings[0].Code != "tables" {
		t.Errorf("a missing table: %+v", r.Warnings)
	}
}

func TestWriteTablesRefusals(t *testing.T) {
	e := setup(t)
	root := e.linked(t, "main")
	testpack.Git(t, root, "add", "-A")
	testpack.Git(t, root, "commit", "-q", "-m", "linked")
	writeFile(t, root, "work/tasks/T-0902-c.md", f1Todo)
	wt := filepath.Join(e.tmp, "branch")
	testpack.Git(t, root, "worktree", "add", "-q", "-b", "branch", wt)
	before := snapshot(t, wt)
	_, werr := WriteTables(wt)
	if werr == nil || werr.Code != "not-main-checkout" || werr.Exit != ExitState || !strings.Contains(werr.Next, filepath.ToSlash(root)) ||
		!strings.Contains(werr.What, "worktree") || werr.Object().Next.Who != "agent" {
		t.Fatalf("a worktree: %+v", werr)
	}
	if after := snapshot(t, wt); len(after) != len(before) || after[workspace.TasksTableFile] != before[workspace.TasksTableFile] {
		t.Errorf("the refusal wrote something")
	}
	// The worktree's check still warns: its table against a rebuild from the main checkout's task files, with the
	// main checkout's command to run.
	r, err := checkLocal(t, wt, e.home)
	if err != nil || len(r.Findings) != 0 || len(r.Warnings) != 1 || r.Warnings[0].Code != "tables" ||
		!strings.Contains(r.Warnings[0].Next, "main checkout, "+filepath.ToSlash(root)+": from there, run: bonsai check --write") {
		t.Errorf("a worktree's check: %v %+v %+v", err, r.Findings, r.Warnings)
	}
	// Not linked, and not a checkout.
	if _, werr := WriteTables(testpack.Project(t, e.tmp, "bare")); werr == nil || werr.Code != "not-linked" || werr.Exit != ExitState {
		t.Errorf("not linked: %+v", werr)
	}
	if _, werr := WriteTables(t.TempDir()); werr == nil || werr.Code != "not-a-checkout" || werr.Exit != ExitState {
		t.Errorf("not a checkout: %+v", werr)
	}
}
