package config

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

const lockFileName = ".bonsai-lock.yaml"

// FileEntry records a single generated file in the lock file.
type FileEntry struct {
	Hash   string `yaml:"hash"`
	Source string `yaml:"source,omitempty"`
}

// LockFile tracks all files generated by Bonsai.
type LockFile struct {
	Version int                   `yaml:"version"`
	Files   map[string]*FileEntry `yaml:"files"`
}

// NewLockFile creates an empty lock file.
func NewLockFile() *LockFile {
	return &LockFile{Version: 1, Files: make(map[string]*FileEntry)}
}

// LoadLockFile reads the lock file from disk. Returns a new empty lock file
// if the file doesn't exist (first run / migration case).
func LoadLockFile(projectRoot string) (*LockFile, error) {
	path := filepath.Join(projectRoot, lockFileName)
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return NewLockFile(), nil
	}
	if err != nil {
		return nil, err
	}
	var lf LockFile
	if err := yaml.Unmarshal(data, &lf); err != nil {
		return nil, err
	}
	if lf.Files == nil {
		lf.Files = make(map[string]*FileEntry)
	}
	return &lf, nil
}

// Save writes the lock file to disk.
func (lf *LockFile) Save(projectRoot string) error {
	data, err := yaml.Marshal(lf)
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(projectRoot, lockFileName), data, 0644)
}

// ContentHash computes the sha256 hex digest of content bytes.
func ContentHash(content []byte) string {
	h := sha256.Sum256(content)
	return hex.EncodeToString(h[:])
}

// Track records a file in the lock file.
func (lf *LockFile) Track(relPath string, content []byte, source string) {
	lf.Files[relPath] = &FileEntry{
		Hash:   ContentHash(content),
		Source: source,
	}
}

// Untrack removes a file from the lock file.
func (lf *LockFile) Untrack(relPath string) {
	delete(lf.Files, relPath)
}

// IsModified checks whether the file on disk differs from the lock file hash.
// Returns exists=false if the file is not on disk (safe to write).
// Returns modified=true if the file exists but differs from the lock hash,
// or if the file exists but has no lock entry (conservative: treat as user-owned).
func (lf *LockFile) IsModified(projectRoot, relPath string) (exists, modified bool) {
	absPath := filepath.Join(projectRoot, relPath)
	data, err := os.ReadFile(absPath)
	if err != nil {
		return false, false
	}
	entry, tracked := lf.Files[relPath]
	if !tracked {
		return true, true
	}
	diskHash := ContentHash(data)
	return true, diskHash != entry.Hash
}
