package format

import (
	"strings"
	"testing"
)

// The ask schema's description of type names the known types; AskTypes, their one home in code, holds the same words
// in the same order.
func TestAskTypesAreTheSchemas(t *testing.T) {
	desc := sub(props(MustLookup("ask").Schema()), "type").String("description")
	var words []string
	for _, w := range AskTypes {
		words = append(words, w.Word)
		if !strings.Contains(desc, w.Word) {
			t.Errorf("ask type %s is in format.AskTypes but not in the ask schema's description of type", w.Word)
		}
		if w.Means == "" {
			t.Errorf("ask type %s has no meaning", w.Word)
		}
	}
	// The schema names them in this order: Answer, Decide, Look or Play from agents, Bless from the ladder.
	at := -1
	for _, w := range words {
		i := strings.Index(desc, w)
		if i <= at {
			t.Errorf("ask type %s is out of the schema's order", w)
		}
		at = i
	}
}

// ExitCodes: codes 0 to 5 for every word but hook, in order, then hook's two; each with its words.
func TestExitCodesTable(t *testing.T) {
	for i, e := range ExitCodes {
		if e.Short == "" || e.Means == "" {
			t.Errorf("exit code row %d has no words", i)
		}
		switch {
		case i < 6 && (e.Code != i || e.Applies != ExitEveryWord):
			t.Errorf("row %d: code %d for %q, want %d for every word but hook", i, e.Code, e.Applies, i)
		case i >= 6 && e.Applies != ExitHook:
			t.Errorf("row %d: %q, want hook's", i, e.Applies)
		}
	}
	if len(ExitCodes) != 8 {
		t.Errorf("%d exit codes, want 6 and hook's 2", len(ExitCodes))
	}
}

// The log's events and categories have one home, their Go tables: every word has its line, no word repeats, the
// schema's descriptions of event and category name the commands that print them and copy none of the words, and
// bonsai check --schema bonsai.log prints every one (set 6).
func TestLogListsHaveOneHome(t *testing.T) {
	f := MustLookup("log")
	ps := props(f.Schema())
	check := func(field string, words []Word, copies []string) {
		t.Helper()
		seen := map[string]bool{}
		for _, w := range words {
			if w.Word == "" || w.Means == "" {
				t.Errorf("%s: the word %q has no meaning", field, w.Word)
			}
			if seen[w.Word] {
				t.Errorf("%s: the word %s is listed twice", field, w.Word)
			}
			seen[w.Word] = true
		}
		desc := sub(ps, field).String("description")
		if !strings.Contains(desc, "bonsai check --schema bonsai.log") {
			t.Errorf("the schema's description of %s does not name bonsai check --schema bonsai.log", field)
		}
		for _, c := range copies {
			if strings.Contains(desc, c) {
				t.Errorf("the schema's description of %s copies the word %s: the Go table is its one home", field, c)
			}
		}
		if !strings.Contains(f.Describe(), "Known words") && !strings.Contains(f.Describe(), "known words") {
			t.Errorf("--schema bonsai.log prints no known words")
		}
		for _, w := range words {
			if !strings.Contains(f.Describe(), w.Word) {
				t.Errorf("--schema bonsai.log does not print the %s word %s", field, w.Word)
			}
		}
	}
	check("event", LogEvents, []string{"session_start", "session_end", "tool_start", "tool_end", "tool_fail", "subagent_start", "subagent_stop"})
	check("category", LogCategories, []string{"Search", "Shell", "Ladder", "MCP", "Agent", "Web", "Other"})
	if len(LogEvents) != 16 || len(LogCategories) != 10 {
		t.Errorf("contract section 8.2 has sixteen events and ten categories, the tables %d and %d", len(LogEvents), len(LogCategories))
	}
}

// A table written before set 6 has no Subagent column: it reads, every row's subagent null, and a table written now
// has the column and reads back with it. The header is matched exactly, so a header of neither shape is refused.
func TestSessionsReadsTheOldHeader(t *testing.T) {
	const front = "---\nformat: bonsai.sessions/1   # generated by bonsai check --write from the log; never edit by hand\n---\n"
	const tail = "\nHours per task and role (a subagent run lies inside its session's row, so the two are never added):\n\n" +
		"| Task | Role | Kind | Hours |\n|---|---|---|---|\n"
	old := "| Session | Kind | Task | Role | Model | Start | End | Minutes |\n|---|---|---|---|---|---|---|---|\n"
	empty, err := ReadSessions([]byte(front + old + tail))
	if err != nil {
		t.Fatalf("a table 5.1's init wrote (no rows, the old header) does not read: %v", err)
	}
	if len(empty.Sessions) != 0 {
		t.Errorf("an empty table read %d rows", len(empty.Sessions))
	}
	withRow, err := ReadSessions([]byte(front + old + "| 3f2a9c1e | session | T-0901 | builder | | 2026-10-08 09:05 | 2026-10-08 10:35 | 90 |\n" + tail))
	if err != nil {
		t.Fatalf("a table with a row and the old header does not read: %v", err)
	}
	if len(withRow.Sessions) != 1 || withRow.Sessions[0].Subagent != nil || withRow.Sessions[0].Minutes != 90 || withRow.Sessions[0].Model != nil {
		t.Errorf("the old row read as %+v", withRow.Sessions)
	}
	// Writing it again gives the new header, with the subagent cell empty, and that reads back the same.
	out, err := withRow.Encode()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), "| Minutes | Subagent |\n|---|---|---|---|---|---|---|---|---|\n") ||
		!strings.Contains(string(out), "| 90 | |\n") {
		t.Errorf("the table written is not the nine-column one:\n%s", out)
	}
	again, err := ReadSessions(out)
	if err != nil || again.Sessions[0].Subagent != nil {
		t.Fatalf("what was written does not read back: %v", err)
	}
	// A subagent run's id round-trips.
	id := "e7c4b1d2"
	withRow.Sessions = append(withRow.Sessions, SessionRow{Session: "3f2a9c1e", Kind: "subagent", Task: "T-0901", Start: "2026-10-08 10:00",
		End: "2026-10-08 10:30", Minutes: 30, Subagent: &id})
	out, err = withRow.Encode()
	if err != nil {
		t.Fatal(err)
	}
	again, err = ReadSessions(out)
	if err != nil || len(again.Sessions) != 2 || again.Sessions[1].Subagent == nil || *again.Sessions[1].Subagent != id {
		t.Fatalf("a subagent run's row does not round-trip: %v\n%s", err, out)
	}
	// Neither header: refused, naming the line.
	if _, err := ReadSessions([]byte(front + "| Session | Kind | Task | Role | Model | Start | End |\n|---|---|---|---|---|---|---|\n" + tail)); err == nil {
		t.Errorf("a table with a header of neither shape was read")
	}
	// A row of the wrong width for its header is refused: nine cells under the old header.
	if _, err := ReadSessions([]byte(front + old + "| a | b | c | d | e | f | g | 1 | h |\n" + tail)); err == nil {
		t.Errorf("a nine-cell row under the old header was read")
	}
}

// The four words 5.2's commands need are in the error words, each with a meaning and who takes the step.
func TestSetSixErrorWords(t *testing.T) {
	for _, code := range []string{"ask-not-open", "answer-own-session", "label-not-defined", "session-not-found"} {
		w, ok := ErrorWord(code)
		if !ok || w.Means == "" || (w.Who != "agent" && w.Who != "person") {
			t.Errorf("the error word %s is missing or incomplete: %+v", code, w)
		}
	}
}

// Check's notes and unlink's left-in-place lines are fields of their documents (set 6), written as lists, [] for none.
func TestNotesAndLeftAreWritten(t *testing.T) {
	c := &Check{Notes: []string{"a note"}}
	out, err := c.Encode()
	if err != nil || !strings.Contains(string(out), `"notes": [`) || !strings.Contains(string(out), `"a note"`) {
		t.Errorf("check does not write its notes (%v):\n%s", err, out)
	}
	back, err := ReadCheck(out)
	if err != nil || len(back.Notes) != 1 {
		t.Errorf("check's notes do not read back: %v", err)
	}
	old, err := ReadCheck([]byte(`{"format": "bonsai.check/1", "findings": [], "warnings": [], "error": null}`))
	if err != nil || old.Notes != nil {
		t.Errorf("a check document written before set 6 reads with notes null: %v %v", err, old)
	}
	ch := &Changes{Command: "unlink", Result: "applied", Left: []string{".bonsai/local/: this checkout's log"}}
	out, err = ch.Encode()
	if err != nil || !strings.Contains(string(out), `"left": [`) {
		t.Errorf("changes does not write left (%v):\n%s", err, out)
	}
}
