package format

// The two generated tables (contract §7.5, spec §6): .bonsai/tasks.md (bonsai.tasks/1) and .bonsai/sessions.md
// (bonsai.sessions/1). Bonsai writes them (check --write, steps 5.1.8 and 5.2.3; init) and reads them back; no reader
// grants anything by them. A table is a frontmatter (its format line, with the comment saying it is generated) and a
// body a JSON Schema cannot describe, written and read as formats/README.md ("The two tables' bodies") says:
//   - tasks.md: the line "Active task when none is named: <id>" or "... none (<why>)", a blank line, the table
//     | Task | Title | Status | Lane | Started | Finished |, its |---| line, one row per task (newest id first, the
//     writer's caller's order);
//   - sessions.md: the table | Session | Kind | Task | Role | Model | Start | End | Minutes |, its |---| line and one
//     row per session or subagent run; a blank line; the hours line; a blank line; the table
//     | Task | Role | Kind | Hours |, its |---| line and one row per task, role and kind;
//   - in both, a null is an empty cell, a | inside a cell is written \|, and nothing else is escaped.
//
// A cell's text is written as valid UTF-8: a format-0 title can hold a lone UTF-16 surrogate, which internal/reader's
// format-0 mode keeps as its three WTF-8 bytes (JavaScript's own text); written, it becomes U+FFFD, as Node writes a
// lone surrogate into a UTF-8 file (5.1.2's verifier: such a value is never written through encoding/json either).

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/LastStep/Bonsai/internal/schema"
)

// Tasks is the tasks table.
type Tasks struct {
	Active TasksActive   `json:"active"` // the body's active line
	Tasks  []TaskRow     `json:"tasks"`  // the rows, as written
	Extra  schema.Object `json:"-"`      // frontmatter fields this Bonsai does not know
}

// TasksActive is the active task when none is named (contract §13's step 2): an id, or none and why.
type TasksActive struct {
	ID    *string       `json:"id"`
	Why   *string       `json:"why"`
	Extra schema.Object `json:"-"`
}

// TaskRow is one task's row.
type TaskRow struct {
	ID       string        `json:"id"`
	Title    string        `json:"title"`
	Status   string        `json:"status"`
	Lane     *string       `json:"lane"`
	Started  *string       `json:"started"`
	Finished *string       `json:"finished"`
	Extra    schema.Object `json:"-"`
}

// Sessions is the sessions table.
type Sessions struct {
	Sessions []SessionRow  `json:"sessions"`
	Hours    []HoursRow    `json:"hours"`
	Extra    schema.Object `json:"-"`
}

// SessionRow is one session's or subagent run's row.
type SessionRow struct {
	Session string        `json:"session"` // the session id's first 8 characters
	Kind    string        `json:"kind"`    // the closed list: session, subagent
	Task    string        `json:"task"`    // a task id, or none
	Role    *string       `json:"role"`
	Model   *string       `json:"model"`
	Start   string        `json:"start"` // YYYY-MM-DD HH:MM
	End     string        `json:"end"`
	Minutes int64         `json:"minutes"`
	Extra   schema.Object `json:"-"`
}

// HoursRow is one task, role and kind's hours.
type HoursRow struct {
	Task  string        `json:"task"`
	Role  *string       `json:"role"`
	Kind  string        `json:"kind"` // the closed list: session, subagent
	Hours json.Number   `json:"hours"`
	Extra schema.Object `json:"-"`
}

const (
	tasksComment    = "generated by bonsai check --write from the task files; never edit by hand"
	sessionsComment = "generated by bonsai check --write from the log; never edit by hand"
	activeLine      = "Active task when none is named: "
	hoursLine       = "Hours per task and role (a subagent run lies inside its session's row, so the two are never added):"
)

var (
	tasksHeader    = []string{"Task", "Title", "Status", "Lane", "Started", "Finished"}
	sessionsHeader = []string{"Session", "Kind", "Task", "Role", "Model", "Start", "End", "Minutes"}
	hoursHeader    = []string{"Task", "Role", "Kind", "Hours"}
)

// Encode writes the tasks table, held to bonsai.tasks/1.
func (t *Tasks) Encode() ([]byte, error) {
	f := MustLookup("tasks")
	doc, err := f.tableDoc(t)
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	if err := frontmatter(&b, f, tasksComment, t.Extra); err != nil {
		return nil, err
	}
	switch {
	case t.Active.ID != nil:
		b.WriteString(activeLine + cell(*t.Active.ID) + "\n")
	case t.Active.Why != nil:
		b.WriteString(activeLine + "none (" + cell(*t.Active.Why) + ")\n")
	default:
		b.WriteString(activeLine + "none\n")
	}
	b.WriteString("\n")
	rows, _ := doc.Get("tasks")
	writeTable(&b, tasksHeader, rows.([]any), []string{"id", "title", "status", "lane", "started", "finished"})
	return []byte(b.String()), nil
}

// Encode writes the sessions table, held to bonsai.sessions/1.
func (s *Sessions) Encode() ([]byte, error) {
	f := MustLookup("sessions")
	doc, err := f.tableDoc(s)
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	if err := frontmatter(&b, f, sessionsComment, s.Extra); err != nil {
		return nil, err
	}
	rows, _ := doc.Get("sessions")
	writeTable(&b, sessionsHeader, rows.([]any), []string{"session", "kind", "task", "role", "model", "start", "end", "minutes"})
	b.WriteString("\n" + hoursLine + "\n\n")
	hours, _ := doc.Get("hours")
	writeTable(&b, hoursHeader, hours.([]any), []string{"task", "role", "kind", "hours"})
	return []byte(b.String()), nil
}

// tableDoc gives a table's document once Check passes.
func (f *Format) tableDoc(v any) (schema.Object, error) {
	doc, err := f.Document(v)
	if err != nil {
		return nil, err
	}
	return doc, f.Check(doc)
}

// frontmatter writes a table's frontmatter: its format line with the comment saying it is generated, then any field
// this Bonsai does not know, kept.
func frontmatter(b *strings.Builder, f *Format, comment string, extra schema.Object) error {
	b.WriteString("---\nformat: " + f.Versioned() + "   # " + comment + "\n")
	if len(extra) > 0 {
		y, err := yamlDocument(append(schema.Object{{Key: "format", Value: f.Versioned()}}, normalize(extra).(schema.Object)...), YAMLOptions{})
		if err != nil {
			return err
		}
		_, rest, _ := strings.Cut(string(y), "\n")
		b.WriteString(rest)
	}
	b.WriteString("---\n")
	return nil
}

// writeTable writes a header, its |---| line and one row per item, the item's fields in keys' order.
func writeTable(b *strings.Builder, header []string, rows []any, keys []string) {
	writeRow(b, header)
	b.WriteString("|" + strings.Repeat("---|", len(header)) + "\n")
	for _, r := range rows {
		o := r.(schema.Object)
		cells := make([]string, len(keys))
		for i, k := range keys {
			v, _ := o.Get(k)
			switch x := v.(type) {
			case string:
				cells[i] = cell(x)
			case json.Number:
				cells[i] = string(x)
			}
		}
		writeRow(b, cells)
	}
}

func writeRow(b *strings.Builder, cells []string) {
	b.WriteString("|")
	for _, c := range cells {
		if c == "" {
			b.WriteString(" |")
		} else {
			b.WriteString(" " + c + " |")
		}
	}
	b.WriteString("\n")
}

// cell writes text for a cell: a | as \|, and valid UTF-8 (a lone surrogate's WTF-8 bytes become U+FFFD).
func cell(s string) string {
	return strings.ReplaceAll(strings.ToValidUTF8(s, "�"), "|", `\|`)
}

// ReadTasks reads the tasks table's bytes: the frontmatter, then the body.
func ReadTasks(raw []byte) (*Tasks, error) {
	f := MustLookup("tasks")
	front, body, first, err := f.tableParts(raw)
	if err != nil {
		return nil, err
	}
	tb := &tableBody{f: f, lines: body, no: first}
	active := schema.Object{{Key: "id", Value: nil}, {Key: "why", Value: nil}}
	l, n := tb.next()
	text, ok := strings.CutPrefix(l, activeLine)
	if !ok {
		return nil, f.refuse(n, "active", "the body's first line is not %q", activeLine+"<id>")
	}
	switch {
	case text == "none":
	case strings.HasPrefix(text, "none (") && strings.HasSuffix(text, ")"):
		active[1].Value = uncell(text[len("none (") : len(text)-1])
	default:
		active[0].Value = uncell(text)
	}
	if l, n := tb.next(); l != "" {
		return nil, f.refuse(n, "", "no blank line after the active line")
	}
	rows, err := tb.table(tasksHeader, "tasks", []string{"id", "title", "status", "lane", "started", "finished"},
		map[string]bool{"lane": true, "started": true, "finished": true}, nil)
	if err != nil {
		return nil, err
	}
	if err := tb.end(); err != nil {
		return nil, err
	}
	doc := append(front, schema.Member{Key: "active", Value: active}, schema.Member{Key: "tasks", Value: rows})
	if doc, err = f.hold(doc, nil); err != nil {
		return nil, err
	}
	t := &Tasks{}
	return t, f.Bind(doc, t)
}

// ReadSessions reads the sessions table's bytes: the frontmatter, then the body.
func ReadSessions(raw []byte) (*Sessions, error) {
	f := MustLookup("sessions")
	front, body, first, err := f.tableParts(raw)
	if err != nil {
		return nil, err
	}
	tb := &tableBody{f: f, lines: body, no: first}
	sessions, err := tb.table(sessionsHeader, "sessions", []string{"session", "kind", "task", "role", "model", "start", "end", "minutes"},
		map[string]bool{"role": true, "model": true}, map[string]bool{"minutes": true})
	if err != nil {
		return nil, err
	}
	for _, want := range []string{"", hoursLine, ""} {
		if l, n := tb.next(); l != want {
			return nil, f.refuse(n, "hours", "the line is not %q", want)
		}
	}
	hours, err := tb.table(hoursHeader, "hours", []string{"task", "role", "kind", "hours"},
		map[string]bool{"role": true}, map[string]bool{"hours": true})
	if err != nil {
		return nil, err
	}
	if err := tb.end(); err != nil {
		return nil, err
	}
	doc := append(front, schema.Member{Key: "sessions", Value: sessions}, schema.Member{Key: "hours", Value: hours})
	if doc, err = f.hold(doc, nil); err != nil {
		return nil, err
	}
	s := &Sessions{}
	return s, f.Bind(doc, s)
}

// tableParts reads a table's frontmatter under format 1 and gives the body's lines (CRLF read as LF) with the
// first one's line number.
func (f *Format) tableParts(raw []byte) (front schema.Object, body []string, first int, err error) {
	front, _, err = f.ReadYAML(raw)
	if err != nil {
		return nil, nil, 0, err
	}
	lines := strings.Split(string(lf(raw)), "\n")
	if n := len(lines); n > 0 && lines[n-1] == "" {
		lines = lines[:n-1]
	}
	for i := 1; i < len(lines); i++ {
		if lines[i] == "---" {
			return front, lines[i+1:], i + 2, nil
		}
	}
	return nil, nil, 0, f.refuse(1, "", "has no closing --- line after its frontmatter")
}

// tableBody reads a table's body line by line.
type tableBody struct {
	f     *Format
	lines []string
	at    int
	no    int // the first body line's number in the file
}

// next gives the next line and its number; past the end, "" and the line after the last.
func (t *tableBody) next() (string, int) {
	n := t.no + t.at
	if t.at >= len(t.lines) {
		return "", n
	}
	t.at++
	return t.lines[t.at-1], n
}

// end refuses anything but blank lines after the last table.
func (t *tableBody) end() error {
	for t.at < len(t.lines) {
		if l, n := t.next(); strings.TrimSpace(l) != "" {
			return t.f.refuse(n, "", "a line follows the last table: %s", quoteASCII(l))
		}
	}
	return nil
}

// table reads a header, its |---| line and the rows up to a blank line or the end, each row's cells into keys: an
// empty cell is null where nullable says so, and a cell of numbers says which cells hold a number.
func (t *tableBody) table(header []string, field string, keys []string, nullable, numbers map[string]bool) ([]any, error) {
	if l, n := t.next(); !equalCells(l, header) {
		return nil, t.f.refuse(n, field, "the line is not the table's header %s", quoteASCII(joinRow(header)))
	}
	if l, n := t.next(); l != "|"+strings.Repeat("---|", len(header)) {
		return nil, t.f.refuse(n, field, "the line under the header is not %s", "|"+strings.Repeat("---|", len(header)))
	}
	rows := []any{}
	for t.at < len(t.lines) && t.lines[t.at] != "" {
		l, n := t.next()
		cells, ok := splitRow(l)
		if !ok || len(cells) != len(keys) {
			return nil, t.f.refuse(n, fmt.Sprintf("%s[%d]", field, len(rows)), "the row does not hold %d cells: %s",
				len(keys), quoteASCII(l))
		}
		o := schema.Object{}
		for i, k := range keys {
			var v any = cells[i]
			switch {
			case cells[i] == "" && nullable[k]:
				v = nil
			case numbers[k] && isNumber(cells[i]):
				v = json.Number(cells[i])
			}
			o = append(o, schema.Member{Key: k, Value: v})
		}
		rows = append(rows, o)
	}
	return rows, nil
}

func joinRow(cells []string) string {
	var b strings.Builder
	writeRow(&b, cells)
	return strings.TrimSuffix(b.String(), "\n")
}

func equalCells(l string, header []string) bool { return l == joinRow(header) }

// splitRow cuts a row into its cells: between unescaped |, one space taken off each side, \| read as |.
func splitRow(l string) ([]string, bool) {
	if !strings.HasPrefix(l, "|") || !strings.HasSuffix(l, "|") || len(l) < 2 {
		return nil, false
	}
	inner := l[1 : len(l)-1]
	var cells []string
	var cur strings.Builder
	for i := 0; i < len(inner); i++ {
		switch {
		case inner[i] == '\\' && i+1 < len(inner) && inner[i+1] == '|':
			cur.WriteString(`\|`)
			i++
		case inner[i] == '|':
			cells = append(cells, cur.String())
			cur.Reset()
		default:
			cur.WriteByte(inner[i])
		}
	}
	cells = append(cells, cur.String())
	for i, c := range cells {
		c = strings.TrimPrefix(c, " ")
		c = strings.TrimSuffix(c, " ")
		cells[i] = uncell(c)
	}
	return cells, true
}

func uncell(s string) string { return strings.ReplaceAll(s, `\|`, "|") }

// isNumber reports whether a cell is a JSON number.
func isNumber(s string) bool {
	t := strings.TrimPrefix(s, "-")
	whole, frac, hasDot := strings.Cut(t, ".")
	if !digits(whole) || (len(whole) > 1 && whole[0] == '0') {
		return false
	}
	return !hasDot || digits(frac)
}
